services:
  postgres:
    image: registry.gitlab.com/paganiniinformatica/paganini-app-boilerplate/db:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/postgres/postgres.Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_CONNECTION_DATABASE:-paganini_app_boilerplate}
      POSTGRES_USER: ${DATABASE_CONNECTION_USERNAME:-app_user}
      POSTGRES_PASSWORD: ${DATABASE_CONNECTION_PASSWORD:-development}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d paganini_app_boilerplate"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: registry.gitlab.com/paganiniinformatica/paganini-app-boilerplate/app:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/app/app.Dockerfile
    restart: unless-stopped
    ports:
      - "3500:3500"
    environment:
      # Command to run
      CMD: start

      # Environment variables
      APP_DEFAULT_THEME: ${APP_DEFAULT_THEME:-}
      APP_ENV: ${APP_ENV:-}
      APP_NAME: ${APP_NAME:-}
      APP_PORT: ${APP_PORT:-}
      APP_TIMEOUT: ${APP_TIMEOUT:-}
      APP_TIMEZONE: ${APP_TIMEZONE:-}
      APP_URL: ${APP_URL:-}
      APP_VERSION: ${APP_VERSION:-}
      AUTH_BASE_PATH: ${AUTH_BASE_PATH:-}
      AUTH_BASE_URL: ${AUTH_BASE_URL:-}
      AUTH_CROSS_SUB_DOMAIN_COOKIES_ENABLED: ${AUTH_CROSS_SUB_DOMAIN_COOKIES_ENABLED:-}
      AUTH_ENABLE_SIGN_UP: ${AUTH_ENABLE_SIGN_UP:-}
      AUTH_LOGIN_METHOD: ${AUTH_LOGIN_METHOD:-}
      AUTH_REQUIRE_VERIFICATION: ${AUTH_REQUIRE_VERIFICATION:-}
      AUTH_SECRET: ${AUTH_SECRET:-}
      AUTH_SESSION_COOKIE_NAME: ${AUTH_SESSION_COOKIE_NAME:-}
      AUTH_SESSION_MAX_AGE: ${AUTH_SESSION_MAX_AGE:-}
      AUTH_SOCIAL_LOGIN_APPLE_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_APPLE_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_APPLE_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_APPLE_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_APPLE_ENABLED: ${AUTH_SOCIAL_LOGIN_APPLE_ENABLED:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_ENABLED: ${AUTH_SOCIAL_LOGIN_GOOGLE_ENABLED:-}
      AUTH_SOCIAL_LOGIN_META_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_META_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_META_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_META_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_META_ENABLED: ${AUTH_SOCIAL_LOGIN_META_ENABLED:-}
      CACHE_MAX_VALUE_SIZE: ${CACHE_MAX_VALUE_SIZE:-}
      CNPJJA_API_KEY: ${CNPJJA_API_KEY:-}
      CNPJJA_BASE_URL: ${CNPJJA_BASE_URL:-}
      CNPJJA_MAX_RETRIES: ${CNPJJA_MAX_RETRIES:-}
      CNPJJA_TIMEOUT: ${CNPJJA_TIMEOUT:-}
      COLORS_CHART_CYAN_LIGHT: ${COLORS_CHART_CYAN_LIGHT:-}
      COLORS_CHART_CYAN_VERY_LIGHT: ${COLORS_CHART_CYAN_VERY_LIGHT:-}
      COLORS_CYAN: ${COLORS_CYAN:-}
      COLORS_CYAN2: ${COLORS_CYAN2:-}
      COLORS_CYAN3: ${COLORS_CYAN3:-}
      COLORS_CYAN4: ${COLORS_CYAN4:-}
      COLORS_CYAN5: ${COLORS_CYAN5:-}
      COLORS_DARK_DARKBLUE: ${COLORS_DARK_DARKBLUE:-}
      COLORS_DARK_DARKBLUE2: ${COLORS_DARK_DARKBLUE2:-}
      COLORS_DARK_DARKBLUE3: ${COLORS_DARK_DARKBLUE3:-}
      COLORS_DARK_DARKBLUE4: ${COLORS_DARK_DARKBLUE4:-}
      COLORS_DARK_SLATE: ${COLORS_DARK_SLATE:-}
      COLORS_DARK_SLATE2: ${COLORS_DARK_SLATE2:-}
      COLORS_DARK_SLATE3: ${COLORS_DARK_SLATE3:-}
      COLORS_DARK_TEXT_PRIMARY: ${COLORS_DARK_TEXT_PRIMARY:-}
      COLORS_DARK_TEXT_QUATERNARY: ${COLORS_DARK_TEXT_QUATERNARY:-}
      COLORS_DARK_TEXT_SECONDARY: ${COLORS_DARK_TEXT_SECONDARY:-}
      COLORS_DARK_TEXT_TERTIARY: ${COLORS_DARK_TEXT_TERTIARY:-}
      COLORS_ERROR_RED: ${COLORS_ERROR_RED:-}
      COLORS_ERROR_RED_LIGHT: ${COLORS_ERROR_RED_LIGHT:-}
      COLORS_GREEN: ${COLORS_GREEN:-}
      COLORS_GREEN2: ${COLORS_GREEN2:-}
      COLORS_LIGHT_DARKBLUE: ${COLORS_LIGHT_DARKBLUE:-}
      COLORS_LIGHT_DARKBLUE2: ${COLORS_LIGHT_DARKBLUE2:-}
      COLORS_LIGHT_DARKBLUE3: ${COLORS_LIGHT_DARKBLUE3:-}
      COLORS_LIGHT_DARKBLUE4: ${COLORS_LIGHT_DARKBLUE4:-}
      COLORS_LIGHT_SLATE: ${COLORS_LIGHT_SLATE:-}
      COLORS_LIGHT_SLATE2: ${COLORS_LIGHT_SLATE2:-}
      COLORS_LIGHT_SLATE3: ${COLORS_LIGHT_SLATE3:-}
      COLORS_LIGHT_TEXT_PRIMARY: ${COLORS_LIGHT_TEXT_PRIMARY:-}
      COLORS_LIGHT_TEXT_QUATERNARY: ${COLORS_LIGHT_TEXT_QUATERNARY:-}
      COLORS_LIGHT_TEXT_SECONDARY: ${COLORS_LIGHT_TEXT_SECONDARY:-}
      COLORS_LIGHT_TEXT_TERTIARY: ${COLORS_LIGHT_TEXT_TERTIARY:-}
      COLORS_OPACITY_TRANSLUCENT: ${COLORS_OPACITY_TRANSLUCENT:-}
      COLORS_OPACITY_TRANSLUCENT2: ${COLORS_OPACITY_TRANSLUCENT2:-}
      COLORS_OPACITY_TRANSLUCENT3: ${COLORS_OPACITY_TRANSLUCENT3:-}
      COLORS_OPACITY_TRANSLUCENT4: ${COLORS_OPACITY_TRANSLUCENT4:-}
      COLORS_OPACITY_TRANSLUCENT_LIGHT: ${COLORS_OPACITY_TRANSLUCENT_LIGHT:-}
      COLORS_OPACITY_TRANSLUCENT_LIGHT2: ${COLORS_OPACITY_TRANSLUCENT_LIGHT2:-}
      COLORS_OPACITY_TRANSLUCENT_MEDIUM: ${COLORS_OPACITY_TRANSLUCENT_MEDIUM:-}
      COLORS_OPACITY_TRANSLUCENT_MEDIUM2: ${COLORS_OPACITY_TRANSLUCENT_MEDIUM2:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT2: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT2:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT3: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT3:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT4: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT4:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT5: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT5:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT6: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT6:-}
      COLORS_PAYMENT_ERROR: ${COLORS_PAYMENT_ERROR:-}
      COLORS_PAYMENT_PLACEHOLDER: ${COLORS_PAYMENT_PLACEHOLDER:-}
      COLORS_PAYMENT_TEXT: ${COLORS_PAYMENT_TEXT:-}
      COLORS_PRIMARY: ${COLORS_PRIMARY:-}
      COLORS_PRIMARY_DARK: ${COLORS_PRIMARY_DARK:-}
      COLORS_PRIMARY_DARKER: ${COLORS_PRIMARY_DARKER:-}
      COLORS_PRIMARY_LIGHT: ${COLORS_PRIMARY_LIGHT:-}
      COLORS_PRIMARY_LIGHTER: ${COLORS_PRIMARY_LIGHTER:-}
      COLORS_QUASAR_ACCENT: ${COLORS_QUASAR_ACCENT:-}
      COLORS_QUASAR_DARK: ${COLORS_QUASAR_DARK:-}
      COLORS_QUASAR_PRIMARY: ${COLORS_QUASAR_PRIMARY:-}
      COLORS_RED: ${COLORS_RED:-}
      COLORS_RED2: ${COLORS_RED2:-}
      COLORS_SOCIAL_INSTAGRAM: ${COLORS_SOCIAL_INSTAGRAM:-}
      COLORS_SOCIAL_MESSENGER: ${COLORS_SOCIAL_MESSENGER:-}
      COLORS_SOCIAL_TELEGRAM: ${COLORS_SOCIAL_TELEGRAM:-}
      COLORS_SOCIAL_WHATSAPP: ${COLORS_SOCIAL_WHATSAPP:-}
      COLORS_WHITE: ${COLORS_WHITE:-}
      COLORS_YELLOW: ${COLORS_YELLOW:-}
      COLORS_YELLOW2: ${COLORS_YELLOW2:-}
      DATABASE_CONNECTION_DATABASE: ${DATABASE_CONNECTION_DATABASE:-}
      DATABASE_CONNECTION_HOST: ${DATABASE_CONNECTION_HOST:-}
      DATABASE_CONNECTION_PASSWORD: ${DATABASE_CONNECTION_PASSWORD:-}
      DATABASE_CONNECTION_PORT: ${DATABASE_CONNECTION_PORT:-}
      DATABASE_CONNECTION_USERNAME: ${DATABASE_CONNECTION_USERNAME:-}
      DATABASE_MIGRATE: ${DATABASE_MIGRATE:-}
      DATABASE_URL: ${DATABASE_URL:-}
      EMAIL_DRIVER: ${EMAIL_DRIVER:-}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-}
      EMAIL_OTP_TEMPLATE_HTML: ${EMAIL_OTP_TEMPLATE_HTML:-}
      EMAIL_OTP_TEMPLATE_SUBJECT: ${EMAIL_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_OTP_TEMPLATE_TEXT: ${EMAIL_OTP_TEMPLATE_TEXT:-}
      EMAIL_REPLY_TO_ADDRESS: ${EMAIL_REPLY_TO_ADDRESS:-}
      EMAIL_REPLY_TO_NAME: ${EMAIL_REPLY_TO_NAME:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_HTML: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_HTML:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_SUBJECT: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_TEXT: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_TEXT:-}
      EMAIL_SES_ACCESS_KEY_ID: ${EMAIL_SES_ACCESS_KEY_ID:-}
      EMAIL_SES_REGION: ${EMAIL_SES_REGION:-}
      EMAIL_SES_SECRET_ACCESS_KEY: ${EMAIL_SES_SECRET_ACCESS_KEY:-}
      EMAIL_SMTP_AUTH_PASSWORD: ${EMAIL_SMTP_AUTH_PASSWORD:-}
      EMAIL_SMTP_AUTH_USER: ${EMAIL_SMTP_AUTH_USER:-}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-}
      EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_HTML: ${EMAIL_VERIFICATION_OTP_TEMPLATE_HTML:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_SUBJECT: ${EMAIL_VERIFICATION_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_TEXT: ${EMAIL_VERIFICATION_OTP_TEMPLATE_TEXT:-}
      FILES_LOCAL_FOLDER: ${FILES_LOCAL_FOLDER:-}
      FILES_LOCAL_SIGNING_KEY: ${FILES_LOCAL_SIGNING_KEY:-}
      FILES_PROVIDER: ${FILES_PROVIDER:-}
      FILES_S3_ACCESS_KEY_ID: ${FILES_S3_ACCESS_KEY_ID:-}
      FILES_S3_BASE_URL: ${FILES_S3_BASE_URL:-}
      FILES_S3_BUCKET: ${FILES_S3_BUCKET:-}
      FILES_S3_REGION: ${FILES_S3_REGION:-}
      FILES_S3_SECRET_ACCESS_KEY: ${FILES_S3_SECRET_ACCESS_KEY:-}
      FIPE_BASE_URL: ${FIPE_BASE_URL:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENAI_MAX_RETRIES: ${OPENAI_MAX_RETRIES:-}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION:-}
      OPENAI_TIMEOUT: ${OPENAI_TIMEOUT:-}
      OPENAI_VALIDATION_MODEL: ${OPENAI_VALIDATION_MODEL:-}
      PAYMENT_ASAAS_API_KEY: ${PAYMENT_ASAAS_API_KEY:-}
      PAYMENT_ASAAS_BASE_URL: ${PAYMENT_ASAAS_BASE_URL:-}
      PAYMENT_ASAAS_ENABLED: ${PAYMENT_ASAAS_ENABLED:-}
      PAYMENT_ASAAS_WEBHOOK_TOKEN: ${PAYMENT_ASAAS_WEBHOOK_TOKEN:-}
      PAYMENT_DEFAULT_PROVIDER: ${PAYMENT_DEFAULT_PROVIDER:-}
      PAYMENT_ENABLED_METHOD_TYPES: ${PAYMENT_ENABLED_METHOD_TYPES:-}
      PAYMENT_MERCADO_PAGO_ACCESS_TOKEN: ${PAYMENT_MERCADO_PAGO_ACCESS_TOKEN:-}
      PAYMENT_MERCADO_PAGO_ENABLED: ${PAYMENT_MERCADO_PAGO_ENABLED:-}
      PAYMENT_MERCADO_PAGO_PUBLIC_KEY: ${PAYMENT_MERCADO_PAGO_PUBLIC_KEY:-}
      PAYMENT_MERCADO_PAGO_WEBHOOK_SECRET: ${PAYMENT_MERCADO_PAGO_WEBHOOK_SECRET:-}
      PAYMENT_PAGAR_ME_API_KEY: ${PAYMENT_PAGAR_ME_API_KEY:-}
      PAYMENT_PAGAR_ME_BASE_URL: ${PAYMENT_PAGAR_ME_BASE_URL:-}
      PAYMENT_PAGAR_ME_ENABLED: ${PAYMENT_PAGAR_ME_ENABLED:-}
      PAYMENT_PAGAR_ME_ENCRYPTION_KEY: ${PAYMENT_PAGAR_ME_ENCRYPTION_KEY:-}
      PAYMENT_PAGAR_ME_WEBHOOK_SECRET: ${PAYMENT_PAGAR_ME_WEBHOOK_SECRET:-}
      PAYMENT_STRIPE_ENABLED: ${PAYMENT_STRIPE_ENABLED:-}
      PAYMENT_STRIPE_PUBLISHABLE_KEY: ${PAYMENT_STRIPE_PUBLISHABLE_KEY:-}
      PAYMENT_STRIPE_SECRET_KEY: ${PAYMENT_STRIPE_SECRET_KEY:-}
      PAYMENT_STRIPE_WEBHOOK_SECRET: ${PAYMENT_STRIPE_WEBHOOK_SECRET:-}
      PREDIAL_AI_API_KEY: ${PREDIAL_AI_API_KEY:-}
      PREDIAL_AI_API_URL: ${PREDIAL_AI_API_URL:-}
      PREDIAL_AI_MODEL: ${PREDIAL_AI_MODEL:-}
      PREDIAL_AI_PROVIDER: ${PREDIAL_AI_PROVIDER:-}
      PREDIAL_ENABLED: ${PREDIAL_ENABLED:-}
      PREDIAL_GEOFENCE_DISTANCE: ${PREDIAL_GEOFENCE_DISTANCE:-}
      PREDIAL_MAX_PHOTO_SIZE: ${PREDIAL_MAX_PHOTO_SIZE:-}
      PREDIAL_NOTIFICATION_ENABLED: ${PREDIAL_NOTIFICATION_ENABLED:-}
      PREDIAL_TRIAL_DURATION_DAYS: ${PREDIAL_TRIAL_DURATION_DAYS:-}
      PUBLIC_APP_NAME: ${PUBLIC_APP_NAME:-}
      PUBLIC_AUTH_BACKGROUND_LOGO_PATH: ${PUBLIC_AUTH_BACKGROUND_LOGO_PATH:-}
      PUBLIC_AUTH_SIDE_LOGO_PATH: ${PUBLIC_AUTH_SIDE_LOGO_PATH:-}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-}
      PUBLIC_DARK_MODE_FOOTER_LOGO_PATH: ${PUBLIC_DARK_MODE_FOOTER_LOGO_PATH:-}
      PUBLIC_DARK_MODE_LOGO_PATH: ${PUBLIC_DARK_MODE_LOGO_PATH:-}
      PUBLIC_DEFAULT_THEME: ${PUBLIC_DEFAULT_THEME:-}
      PUBLIC_FAVICON_PATH: ${PUBLIC_FAVICON_PATH:-}
      PUBLIC_LIGHT_MODE_FOOTER_LOGO_PATH: ${PUBLIC_LIGHT_MODE_FOOTER_LOGO_PATH:-}
      PUBLIC_LIGHT_MODE_LOGO_PATH: ${PUBLIC_LIGHT_MODE_LOGO_PATH:-}
      PUBLIC_MENU_REFRESH_INTERVAL: ${PUBLIC_MENU_REFRESH_INTERVAL:-}
      PUBLIC_SOCIAL_LINKS_FACEBOOK: ${PUBLIC_SOCIAL_LINKS_FACEBOOK:-}
      PUBLIC_SOCIAL_LINKS_GITHUB: ${PUBLIC_SOCIAL_LINKS_GITHUB:-}
      PUBLIC_SOCIAL_LINKS_INSTAGRAM: ${PUBLIC_SOCIAL_LINKS_INSTAGRAM:-}
      PUBLIC_SOCIAL_LINKS_LINKEDIN: ${PUBLIC_SOCIAL_LINKS_LINKEDIN:-}
      PUBLIC_SOCIAL_LINKS_TWITTER: ${PUBLIC_SOCIAL_LINKS_TWITTER:-}
      QUEUES_DEFAULT_JOB_OPTIONS_ATTEMPTS: ${QUEUES_DEFAULT_JOB_OPTIONS_ATTEMPTS:-}
      QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_DELAY: ${QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_DELAY:-}
      QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_TYPE: ${QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_TYPE:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_AGE: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_AGE:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_COUNT: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_COUNT:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_FAIL_AGE: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_FAIL_AGE:-}
      QUEUES_WORKERS_DISABLED: ${QUEUES_WORKERS_DISABLED:-}
      QUEUES_WORKERS_ENABLED: ${QUEUES_WORKERS_ENABLED:-}
      REDIS_AUTH_DB: ${REDIS_AUTH_DB:-}
      REDIS_CACHE_DB: ${REDIS_CACHE_DB:-}
      REDIS_CONNECTION_HOST: ${REDIS_CONNECTION_HOST:-}
      REDIS_CONNECTION_PASSWORD: ${REDIS_CONNECTION_PASSWORD:-}
      REDIS_CONNECTION_PORT: ${REDIS_CONNECTION_PORT:-}
      REDIS_PREFIX: ${REDIS_PREFIX:-}
      REDIS_QUEUE_DB: ${REDIS_QUEUE_DB:-}
      REDIS_URL: ${REDIS_URL:-}
      RPA_CDP_CONNECTION_INITIAL_DELAY: ${RPA_CDP_CONNECTION_INITIAL_DELAY:-}
      RPA_CDP_CONNECTION_RETRIES: ${RPA_CDP_CONNECTION_RETRIES:-}
      RPA_CDP_CONNECTION_RETRY_DELAY: ${RPA_CDP_CONNECTION_RETRY_DELAY:-}
      RPA_CONCURRENCY: ${RPA_CONCURRENCY:-}
      RPA_CONTAINER_BROWSER_IMAGE: ${RPA_CONTAINER_BROWSER_IMAGE:-}
      RPA_CONTAINER_TIMEOUT: ${RPA_CONTAINER_TIMEOUT:-}
      RPA_CONTAINER_USER_AGENT: ${RPA_CONTAINER_USER_AGENT:-}
      RPA_CONTAINER_VIEWPORT_HEIGHT: ${RPA_CONTAINER_VIEWPORT_HEIGHT:-}
      RPA_CONTAINER_VIEWPORT_WIDTH: ${RPA_CONTAINER_VIEWPORT_WIDTH:-}
      RPA_DEBUG: ${RPA_DEBUG:-}
      RPA_ENCRYPTION_KEY: ${RPA_ENCRYPTION_KEY:-}
      RPA_LOCAL_BROWSER_ARGS: ${RPA_LOCAL_BROWSER_ARGS:-}
      RPA_LOCAL_BROWSER_HEADLESS: ${RPA_LOCAL_BROWSER_HEADLESS:-}
      RPA_LOCAL_BROWSER_PERMISSIONS: ${RPA_LOCAL_BROWSER_PERMISSIONS:-}
      RPA_LOCAL_BROWSER_SLOW_MO: ${RPA_LOCAL_BROWSER_SLOW_MO:-}
      RPA_LOCAL_BROWSER_VIEWPORT_HEIGHT: ${RPA_LOCAL_BROWSER_VIEWPORT_HEIGHT:-}
      RPA_LOCAL_BROWSER_VIEWPORT_WIDTH: ${RPA_LOCAL_BROWSER_VIEWPORT_WIDTH:-}
      RPA_MODE: ${RPA_MODE:-}
      RPA_TIMEOUT_BATCH_INACTIVITY_DEFAULT: ${RPA_TIMEOUT_BATCH_INACTIVITY_DEFAULT:-}
      RPA_TIMEOUT_JOB_INACTIVITY_DEFAULT: ${RPA_TIMEOUT_JOB_INACTIVITY_DEFAULT:-}
      SMS_CODE_TEMPLATE: ${SMS_CODE_TEMPLATE:-}
      SMS_DRIVER: ${SMS_DRIVER:-}
      SMS_IAGENTE_BASE_URL: ${SMS_IAGENTE_BASE_URL:-}
      SMS_IAGENTE_PASSWORD: ${SMS_IAGENTE_PASSWORD:-}
      SMS_IAGENTE_USERNAME: ${SMS_IAGENTE_USERNAME:-}
      SMS_RESET_CODE_TEMPLATE: ${SMS_RESET_CODE_TEMPLATE:-}
      SUBSCRIPTIONS_GRACE_PERIOD_DAYS: ${SUBSCRIPTIONS_GRACE_PERIOD_DAYS:-}
      SUBSCRIPTIONS_SCHEDULES_GENERATE_RENEWAL_INVOICES: ${SUBSCRIPTIONS_SCHEDULES_GENERATE_RENEWAL_INVOICES:-}
      SUBSCRIPTIONS_SCHEDULES_INACTIVATE_EXPIRED_SUBSCRIPTIONS: ${SUBSCRIPTIONS_SCHEDULES_INACTIVATE_EXPIRED_SUBSCRIPTIONS:-}
      SUBSCRIPTIONS_SCHEDULES_PROCESS_EXPIRED_TRIALS: ${SUBSCRIPTIONS_SCHEDULES_PROCESS_EXPIRED_TRIALS:-}
      SUBSCRIPTIONS_SCHEDULES_PROCESS_SCHEDULED_DOWNGRADES: ${SUBSCRIPTIONS_SCHEDULES_PROCESS_SCHEDULED_DOWNGRADES:-}

    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "bun", "/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - storage_data:/app/storage

  workers:
    image: registry.gitlab.com/paganiniinformatica/paganini-app-boilerplate/app:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/app/app.Dockerfile
    restart: unless-stopped
    environment:
      # Command to run
      CMD: work

      # Environment variables
      APP_DEFAULT_THEME: ${APP_DEFAULT_THEME:-}
      APP_ENV: ${APP_ENV:-}
      APP_NAME: ${APP_NAME:-}
      APP_PORT: ${APP_PORT:-}
      APP_TIMEOUT: ${APP_TIMEOUT:-}
      APP_TIMEZONE: ${APP_TIMEZONE:-}
      APP_URL: ${APP_URL:-}
      APP_VERSION: ${APP_VERSION:-}
      AUTH_BASE_PATH: ${AUTH_BASE_PATH:-}
      AUTH_BASE_URL: ${AUTH_BASE_URL:-}
      AUTH_CROSS_SUB_DOMAIN_COOKIES_ENABLED: ${AUTH_CROSS_SUB_DOMAIN_COOKIES_ENABLED:-}
      AUTH_ENABLE_SIGN_UP: ${AUTH_ENABLE_SIGN_UP:-}
      AUTH_LOGIN_METHOD: ${AUTH_LOGIN_METHOD:-}
      AUTH_REQUIRE_VERIFICATION: ${AUTH_REQUIRE_VERIFICATION:-}
      AUTH_SECRET: ${AUTH_SECRET:-}
      AUTH_SESSION_COOKIE_NAME: ${AUTH_SESSION_COOKIE_NAME:-}
      AUTH_SESSION_MAX_AGE: ${AUTH_SESSION_MAX_AGE:-}
      AUTH_SOCIAL_LOGIN_APPLE_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_APPLE_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_APPLE_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_APPLE_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_APPLE_ENABLED: ${AUTH_SOCIAL_LOGIN_APPLE_ENABLED:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_ENABLED: ${AUTH_SOCIAL_LOGIN_GOOGLE_ENABLED:-}
      AUTH_SOCIAL_LOGIN_META_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_META_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_META_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_META_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_META_ENABLED: ${AUTH_SOCIAL_LOGIN_META_ENABLED:-}
      CACHE_MAX_VALUE_SIZE: ${CACHE_MAX_VALUE_SIZE:-}
      CNPJJA_API_KEY: ${CNPJJA_API_KEY:-}
      CNPJJA_BASE_URL: ${CNPJJA_BASE_URL:-}
      CNPJJA_MAX_RETRIES: ${CNPJJA_MAX_RETRIES:-}
      CNPJJA_TIMEOUT: ${CNPJJA_TIMEOUT:-}
      COLORS_CHART_CYAN_LIGHT: ${COLORS_CHART_CYAN_LIGHT:-}
      COLORS_CHART_CYAN_VERY_LIGHT: ${COLORS_CHART_CYAN_VERY_LIGHT:-}
      COLORS_CYAN: ${COLORS_CYAN:-}
      COLORS_CYAN2: ${COLORS_CYAN2:-}
      COLORS_CYAN3: ${COLORS_CYAN3:-}
      COLORS_CYAN4: ${COLORS_CYAN4:-}
      COLORS_CYAN5: ${COLORS_CYAN5:-}
      COLORS_DARK_DARKBLUE: ${COLORS_DARK_DARKBLUE:-}
      COLORS_DARK_DARKBLUE2: ${COLORS_DARK_DARKBLUE2:-}
      COLORS_DARK_DARKBLUE3: ${COLORS_DARK_DARKBLUE3:-}
      COLORS_DARK_DARKBLUE4: ${COLORS_DARK_DARKBLUE4:-}
      COLORS_DARK_SLATE: ${COLORS_DARK_SLATE:-}
      COLORS_DARK_SLATE2: ${COLORS_DARK_SLATE2:-}
      COLORS_DARK_SLATE3: ${COLORS_DARK_SLATE3:-}
      COLORS_DARK_TEXT_PRIMARY: ${COLORS_DARK_TEXT_PRIMARY:-}
      COLORS_DARK_TEXT_QUATERNARY: ${COLORS_DARK_TEXT_QUATERNARY:-}
      COLORS_DARK_TEXT_SECONDARY: ${COLORS_DARK_TEXT_SECONDARY:-}
      COLORS_DARK_TEXT_TERTIARY: ${COLORS_DARK_TEXT_TERTIARY:-}
      COLORS_ERROR_RED: ${COLORS_ERROR_RED:-}
      COLORS_ERROR_RED_LIGHT: ${COLORS_ERROR_RED_LIGHT:-}
      COLORS_GREEN: ${COLORS_GREEN:-}
      COLORS_GREEN2: ${COLORS_GREEN2:-}
      COLORS_LIGHT_DARKBLUE: ${COLORS_LIGHT_DARKBLUE:-}
      COLORS_LIGHT_DARKBLUE2: ${COLORS_LIGHT_DARKBLUE2:-}
      COLORS_LIGHT_DARKBLUE3: ${COLORS_LIGHT_DARKBLUE3:-}
      COLORS_LIGHT_DARKBLUE4: ${COLORS_LIGHT_DARKBLUE4:-}
      COLORS_LIGHT_SLATE: ${COLORS_LIGHT_SLATE:-}
      COLORS_LIGHT_SLATE2: ${COLORS_LIGHT_SLATE2:-}
      COLORS_LIGHT_SLATE3: ${COLORS_LIGHT_SLATE3:-}
      COLORS_LIGHT_TEXT_PRIMARY: ${COLORS_LIGHT_TEXT_PRIMARY:-}
      COLORS_LIGHT_TEXT_QUATERNARY: ${COLORS_LIGHT_TEXT_QUATERNARY:-}
      COLORS_LIGHT_TEXT_SECONDARY: ${COLORS_LIGHT_TEXT_SECONDARY:-}
      COLORS_LIGHT_TEXT_TERTIARY: ${COLORS_LIGHT_TEXT_TERTIARY:-}
      COLORS_OPACITY_TRANSLUCENT: ${COLORS_OPACITY_TRANSLUCENT:-}
      COLORS_OPACITY_TRANSLUCENT2: ${COLORS_OPACITY_TRANSLUCENT2:-}
      COLORS_OPACITY_TRANSLUCENT3: ${COLORS_OPACITY_TRANSLUCENT3:-}
      COLORS_OPACITY_TRANSLUCENT4: ${COLORS_OPACITY_TRANSLUCENT4:-}
      COLORS_OPACITY_TRANSLUCENT_LIGHT: ${COLORS_OPACITY_TRANSLUCENT_LIGHT:-}
      COLORS_OPACITY_TRANSLUCENT_LIGHT2: ${COLORS_OPACITY_TRANSLUCENT_LIGHT2:-}
      COLORS_OPACITY_TRANSLUCENT_MEDIUM: ${COLORS_OPACITY_TRANSLUCENT_MEDIUM:-}
      COLORS_OPACITY_TRANSLUCENT_MEDIUM2: ${COLORS_OPACITY_TRANSLUCENT_MEDIUM2:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT2: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT2:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT3: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT3:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT4: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT4:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT5: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT5:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT6: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT6:-}
      COLORS_PAYMENT_ERROR: ${COLORS_PAYMENT_ERROR:-}
      COLORS_PAYMENT_PLACEHOLDER: ${COLORS_PAYMENT_PLACEHOLDER:-}
      COLORS_PAYMENT_TEXT: ${COLORS_PAYMENT_TEXT:-}
      COLORS_PRIMARY: ${COLORS_PRIMARY:-}
      COLORS_PRIMARY_DARK: ${COLORS_PRIMARY_DARK:-}
      COLORS_PRIMARY_DARKER: ${COLORS_PRIMARY_DARKER:-}
      COLORS_PRIMARY_LIGHT: ${COLORS_PRIMARY_LIGHT:-}
      COLORS_PRIMARY_LIGHTER: ${COLORS_PRIMARY_LIGHTER:-}
      COLORS_QUASAR_ACCENT: ${COLORS_QUASAR_ACCENT:-}
      COLORS_QUASAR_DARK: ${COLORS_QUASAR_DARK:-}
      COLORS_QUASAR_PRIMARY: ${COLORS_QUASAR_PRIMARY:-}
      COLORS_RED: ${COLORS_RED:-}
      COLORS_RED2: ${COLORS_RED2:-}
      COLORS_SOCIAL_INSTAGRAM: ${COLORS_SOCIAL_INSTAGRAM:-}
      COLORS_SOCIAL_MESSENGER: ${COLORS_SOCIAL_MESSENGER:-}
      COLORS_SOCIAL_TELEGRAM: ${COLORS_SOCIAL_TELEGRAM:-}
      COLORS_SOCIAL_WHATSAPP: ${COLORS_SOCIAL_WHATSAPP:-}
      COLORS_WHITE: ${COLORS_WHITE:-}
      COLORS_YELLOW: ${COLORS_YELLOW:-}
      COLORS_YELLOW2: ${COLORS_YELLOW2:-}
      DATABASE_CONNECTION_DATABASE: ${DATABASE_CONNECTION_DATABASE:-}
      DATABASE_CONNECTION_HOST: ${DATABASE_CONNECTION_HOST:-}
      DATABASE_CONNECTION_PASSWORD: ${DATABASE_CONNECTION_PASSWORD:-}
      DATABASE_CONNECTION_PORT: ${DATABASE_CONNECTION_PORT:-}
      DATABASE_CONNECTION_USERNAME: ${DATABASE_CONNECTION_USERNAME:-}
      DATABASE_MIGRATE: ${DATABASE_MIGRATE:-}
      DATABASE_URL: ${DATABASE_URL:-}
      EMAIL_DRIVER: ${EMAIL_DRIVER:-}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-}
      EMAIL_OTP_TEMPLATE_HTML: ${EMAIL_OTP_TEMPLATE_HTML:-}
      EMAIL_OTP_TEMPLATE_SUBJECT: ${EMAIL_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_OTP_TEMPLATE_TEXT: ${EMAIL_OTP_TEMPLATE_TEXT:-}
      EMAIL_REPLY_TO_ADDRESS: ${EMAIL_REPLY_TO_ADDRESS:-}
      EMAIL_REPLY_TO_NAME: ${EMAIL_REPLY_TO_NAME:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_HTML: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_HTML:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_SUBJECT: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_TEXT: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_TEXT:-}
      EMAIL_SES_ACCESS_KEY_ID: ${EMAIL_SES_ACCESS_KEY_ID:-}
      EMAIL_SES_REGION: ${EMAIL_SES_REGION:-}
      EMAIL_SES_SECRET_ACCESS_KEY: ${EMAIL_SES_SECRET_ACCESS_KEY:-}
      EMAIL_SMTP_AUTH_PASSWORD: ${EMAIL_SMTP_AUTH_PASSWORD:-}
      EMAIL_SMTP_AUTH_USER: ${EMAIL_SMTP_AUTH_USER:-}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-}
      EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_HTML: ${EMAIL_VERIFICATION_OTP_TEMPLATE_HTML:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_SUBJECT: ${EMAIL_VERIFICATION_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_TEXT: ${EMAIL_VERIFICATION_OTP_TEMPLATE_TEXT:-}
      FILES_LOCAL_FOLDER: ${FILES_LOCAL_FOLDER:-}
      FILES_LOCAL_SIGNING_KEY: ${FILES_LOCAL_SIGNING_KEY:-}
      FILES_PROVIDER: ${FILES_PROVIDER:-}
      FILES_S3_ACCESS_KEY_ID: ${FILES_S3_ACCESS_KEY_ID:-}
      FILES_S3_BASE_URL: ${FILES_S3_BASE_URL:-}
      FILES_S3_BUCKET: ${FILES_S3_BUCKET:-}
      FILES_S3_REGION: ${FILES_S3_REGION:-}
      FILES_S3_SECRET_ACCESS_KEY: ${FILES_S3_SECRET_ACCESS_KEY:-}
      FIPE_BASE_URL: ${FIPE_BASE_URL:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENAI_MAX_RETRIES: ${OPENAI_MAX_RETRIES:-}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION:-}
      OPENAI_TIMEOUT: ${OPENAI_TIMEOUT:-}
      OPENAI_VALIDATION_MODEL: ${OPENAI_VALIDATION_MODEL:-}
      PAYMENT_ASAAS_API_KEY: ${PAYMENT_ASAAS_API_KEY:-}
      PAYMENT_ASAAS_BASE_URL: ${PAYMENT_ASAAS_BASE_URL:-}
      PAYMENT_ASAAS_ENABLED: ${PAYMENT_ASAAS_ENABLED:-}
      PAYMENT_ASAAS_WEBHOOK_TOKEN: ${PAYMENT_ASAAS_WEBHOOK_TOKEN:-}
      PAYMENT_DEFAULT_PROVIDER: ${PAYMENT_DEFAULT_PROVIDER:-}
      PAYMENT_ENABLED_METHOD_TYPES: ${PAYMENT_ENABLED_METHOD_TYPES:-}
      PAYMENT_MERCADO_PAGO_ACCESS_TOKEN: ${PAYMENT_MERCADO_PAGO_ACCESS_TOKEN:-}
      PAYMENT_MERCADO_PAGO_ENABLED: ${PAYMENT_MERCADO_PAGO_ENABLED:-}
      PAYMENT_MERCADO_PAGO_PUBLIC_KEY: ${PAYMENT_MERCADO_PAGO_PUBLIC_KEY:-}
      PAYMENT_MERCADO_PAGO_WEBHOOK_SECRET: ${PAYMENT_MERCADO_PAGO_WEBHOOK_SECRET:-}
      PAYMENT_PAGAR_ME_API_KEY: ${PAYMENT_PAGAR_ME_API_KEY:-}
      PAYMENT_PAGAR_ME_BASE_URL: ${PAYMENT_PAGAR_ME_BASE_URL:-}
      PAYMENT_PAGAR_ME_ENABLED: ${PAYMENT_PAGAR_ME_ENABLED:-}
      PAYMENT_PAGAR_ME_ENCRYPTION_KEY: ${PAYMENT_PAGAR_ME_ENCRYPTION_KEY:-}
      PAYMENT_PAGAR_ME_WEBHOOK_SECRET: ${PAYMENT_PAGAR_ME_WEBHOOK_SECRET:-}
      PAYMENT_STRIPE_ENABLED: ${PAYMENT_STRIPE_ENABLED:-}
      PAYMENT_STRIPE_PUBLISHABLE_KEY: ${PAYMENT_STRIPE_PUBLISHABLE_KEY:-}
      PAYMENT_STRIPE_SECRET_KEY: ${PAYMENT_STRIPE_SECRET_KEY:-}
      PAYMENT_STRIPE_WEBHOOK_SECRET: ${PAYMENT_STRIPE_WEBHOOK_SECRET:-}
      PREDIAL_AI_API_KEY: ${PREDIAL_AI_API_KEY:-}
      PREDIAL_AI_API_URL: ${PREDIAL_AI_API_URL:-}
      PREDIAL_AI_MODEL: ${PREDIAL_AI_MODEL:-}
      PREDIAL_AI_PROVIDER: ${PREDIAL_AI_PROVIDER:-}
      PREDIAL_ENABLED: ${PREDIAL_ENABLED:-}
      PREDIAL_GEOFENCE_DISTANCE: ${PREDIAL_GEOFENCE_DISTANCE:-}
      PREDIAL_MAX_PHOTO_SIZE: ${PREDIAL_MAX_PHOTO_SIZE:-}
      PREDIAL_NOTIFICATION_ENABLED: ${PREDIAL_NOTIFICATION_ENABLED:-}
      PREDIAL_TRIAL_DURATION_DAYS: ${PREDIAL_TRIAL_DURATION_DAYS:-}
      PUBLIC_APP_NAME: ${PUBLIC_APP_NAME:-}
      PUBLIC_AUTH_BACKGROUND_LOGO_PATH: ${PUBLIC_AUTH_BACKGROUND_LOGO_PATH:-}
      PUBLIC_AUTH_SIDE_LOGO_PATH: ${PUBLIC_AUTH_SIDE_LOGO_PATH:-}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-}
      PUBLIC_DARK_MODE_FOOTER_LOGO_PATH: ${PUBLIC_DARK_MODE_FOOTER_LOGO_PATH:-}
      PUBLIC_DARK_MODE_LOGO_PATH: ${PUBLIC_DARK_MODE_LOGO_PATH:-}
      PUBLIC_DEFAULT_THEME: ${PUBLIC_DEFAULT_THEME:-}
      PUBLIC_FAVICON_PATH: ${PUBLIC_FAVICON_PATH:-}
      PUBLIC_LIGHT_MODE_FOOTER_LOGO_PATH: ${PUBLIC_LIGHT_MODE_FOOTER_LOGO_PATH:-}
      PUBLIC_LIGHT_MODE_LOGO_PATH: ${PUBLIC_LIGHT_MODE_LOGO_PATH:-}
      PUBLIC_MENU_REFRESH_INTERVAL: ${PUBLIC_MENU_REFRESH_INTERVAL:-}
      PUBLIC_SOCIAL_LINKS_FACEBOOK: ${PUBLIC_SOCIAL_LINKS_FACEBOOK:-}
      PUBLIC_SOCIAL_LINKS_GITHUB: ${PUBLIC_SOCIAL_LINKS_GITHUB:-}
      PUBLIC_SOCIAL_LINKS_INSTAGRAM: ${PUBLIC_SOCIAL_LINKS_INSTAGRAM:-}
      PUBLIC_SOCIAL_LINKS_LINKEDIN: ${PUBLIC_SOCIAL_LINKS_LINKEDIN:-}
      PUBLIC_SOCIAL_LINKS_TWITTER: ${PUBLIC_SOCIAL_LINKS_TWITTER:-}
      QUEUES_DEFAULT_JOB_OPTIONS_ATTEMPTS: ${QUEUES_DEFAULT_JOB_OPTIONS_ATTEMPTS:-}
      QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_DELAY: ${QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_DELAY:-}
      QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_TYPE: ${QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_TYPE:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_AGE: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_AGE:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_COUNT: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_COUNT:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_FAIL_AGE: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_FAIL_AGE:-}
      QUEUES_WORKERS_DISABLED: ${QUEUES_WORKERS_DISABLED:-}
      QUEUES_WORKERS_ENABLED: ${QUEUES_WORKERS_ENABLED:-}
      REDIS_AUTH_DB: ${REDIS_AUTH_DB:-}
      REDIS_CACHE_DB: ${REDIS_CACHE_DB:-}
      REDIS_CONNECTION_HOST: ${REDIS_CONNECTION_HOST:-}
      REDIS_CONNECTION_PASSWORD: ${REDIS_CONNECTION_PASSWORD:-}
      REDIS_CONNECTION_PORT: ${REDIS_CONNECTION_PORT:-}
      REDIS_PREFIX: ${REDIS_PREFIX:-}
      REDIS_QUEUE_DB: ${REDIS_QUEUE_DB:-}
      REDIS_URL: ${REDIS_URL:-}
      RPA_CDP_CONNECTION_INITIAL_DELAY: ${RPA_CDP_CONNECTION_INITIAL_DELAY:-}
      RPA_CDP_CONNECTION_RETRIES: ${RPA_CDP_CONNECTION_RETRIES:-}
      RPA_CDP_CONNECTION_RETRY_DELAY: ${RPA_CDP_CONNECTION_RETRY_DELAY:-}
      RPA_CONCURRENCY: ${RPA_CONCURRENCY:-}
      RPA_CONTAINER_BROWSER_IMAGE: ${RPA_CONTAINER_BROWSER_IMAGE:-}
      RPA_CONTAINER_TIMEOUT: ${RPA_CONTAINER_TIMEOUT:-}
      RPA_CONTAINER_USER_AGENT: ${RPA_CONTAINER_USER_AGENT:-}
      RPA_CONTAINER_VIEWPORT_HEIGHT: ${RPA_CONTAINER_VIEWPORT_HEIGHT:-}
      RPA_CONTAINER_VIEWPORT_WIDTH: ${RPA_CONTAINER_VIEWPORT_WIDTH:-}
      RPA_DEBUG: ${RPA_DEBUG:-}
      RPA_ENCRYPTION_KEY: ${RPA_ENCRYPTION_KEY:-}
      RPA_LOCAL_BROWSER_ARGS: ${RPA_LOCAL_BROWSER_ARGS:-}
      RPA_LOCAL_BROWSER_HEADLESS: ${RPA_LOCAL_BROWSER_HEADLESS:-}
      RPA_LOCAL_BROWSER_PERMISSIONS: ${RPA_LOCAL_BROWSER_PERMISSIONS:-}
      RPA_LOCAL_BROWSER_SLOW_MO: ${RPA_LOCAL_BROWSER_SLOW_MO:-}
      RPA_LOCAL_BROWSER_VIEWPORT_HEIGHT: ${RPA_LOCAL_BROWSER_VIEWPORT_HEIGHT:-}
      RPA_LOCAL_BROWSER_VIEWPORT_WIDTH: ${RPA_LOCAL_BROWSER_VIEWPORT_WIDTH:-}
      RPA_MODE: ${RPA_MODE:-}
      RPA_TIMEOUT_BATCH_INACTIVITY_DEFAULT: ${RPA_TIMEOUT_BATCH_INACTIVITY_DEFAULT:-}
      RPA_TIMEOUT_JOB_INACTIVITY_DEFAULT: ${RPA_TIMEOUT_JOB_INACTIVITY_DEFAULT:-}
      SMS_CODE_TEMPLATE: ${SMS_CODE_TEMPLATE:-}
      SMS_DRIVER: ${SMS_DRIVER:-}
      SMS_IAGENTE_BASE_URL: ${SMS_IAGENTE_BASE_URL:-}
      SMS_IAGENTE_PASSWORD: ${SMS_IAGENTE_PASSWORD:-}
      SMS_IAGENTE_USERNAME: ${SMS_IAGENTE_USERNAME:-}
      SMS_RESET_CODE_TEMPLATE: ${SMS_RESET_CODE_TEMPLATE:-}
      SUBSCRIPTIONS_GRACE_PERIOD_DAYS: ${SUBSCRIPTIONS_GRACE_PERIOD_DAYS:-}
      SUBSCRIPTIONS_SCHEDULES_GENERATE_RENEWAL_INVOICES: ${SUBSCRIPTIONS_SCHEDULES_GENERATE_RENEWAL_INVOICES:-}
      SUBSCRIPTIONS_SCHEDULES_INACTIVATE_EXPIRED_SUBSCRIPTIONS: ${SUBSCRIPTIONS_SCHEDULES_INACTIVATE_EXPIRED_SUBSCRIPTIONS:-}
      SUBSCRIPTIONS_SCHEDULES_PROCESS_EXPIRED_TRIALS: ${SUBSCRIPTIONS_SCHEDULES_PROCESS_EXPIRED_TRIALS:-}
      SUBSCRIPTIONS_SCHEDULES_PROCESS_SCHEDULED_DOWNGRADES: ${SUBSCRIPTIONS_SCHEDULES_PROCESS_SCHEDULED_DOWNGRADES:-}

    depends_on:
      - postgres
      - redis
    volumes:
      - storage_data:/app/storage
  rpa-workers:
    image: registry.gitlab.com/paganiniinformatica/paganini-app-boilerplate/app:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/app/app.Dockerfile
    restart: unless-stopped
    environment:
      # Command to run
      CMD: work

      # Environment variables
      APP_DEFAULT_THEME: ${APP_DEFAULT_THEME:-}
      APP_ENV: ${APP_ENV:-}
      APP_NAME: ${APP_NAME:-}
      APP_PORT: ${APP_PORT:-}
      APP_TIMEOUT: ${APP_TIMEOUT:-}
      APP_TIMEZONE: ${APP_TIMEZONE:-}
      APP_URL: ${APP_URL:-}
      APP_VERSION: ${APP_VERSION:-}
      AUTH_BASE_PATH: ${AUTH_BASE_PATH:-}
      AUTH_BASE_URL: ${AUTH_BASE_URL:-}
      AUTH_CROSS_SUB_DOMAIN_COOKIES_ENABLED: ${AUTH_CROSS_SUB_DOMAIN_COOKIES_ENABLED:-}
      AUTH_ENABLE_SIGN_UP: ${AUTH_ENABLE_SIGN_UP:-}
      AUTH_LOGIN_METHOD: ${AUTH_LOGIN_METHOD:-}
      AUTH_REQUIRE_VERIFICATION: ${AUTH_REQUIRE_VERIFICATION:-}
      AUTH_SECRET: ${AUTH_SECRET:-}
      AUTH_SESSION_COOKIE_NAME: ${AUTH_SESSION_COOKIE_NAME:-}
      AUTH_SESSION_MAX_AGE: ${AUTH_SESSION_MAX_AGE:-}
      AUTH_SOCIAL_LOGIN_APPLE_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_APPLE_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_APPLE_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_APPLE_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_APPLE_ENABLED: ${AUTH_SOCIAL_LOGIN_APPLE_ENABLED:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_GOOGLE_ENABLED: ${AUTH_SOCIAL_LOGIN_GOOGLE_ENABLED:-}
      AUTH_SOCIAL_LOGIN_META_CLIENT_ID: ${AUTH_SOCIAL_LOGIN_META_CLIENT_ID:-}
      AUTH_SOCIAL_LOGIN_META_CLIENT_SECRET: ${AUTH_SOCIAL_LOGIN_META_CLIENT_SECRET:-}
      AUTH_SOCIAL_LOGIN_META_ENABLED: ${AUTH_SOCIAL_LOGIN_META_ENABLED:-}
      CACHE_MAX_VALUE_SIZE: ${CACHE_MAX_VALUE_SIZE:-}
      CNPJJA_API_KEY: ${CNPJJA_API_KEY:-}
      CNPJJA_BASE_URL: ${CNPJJA_BASE_URL:-}
      CNPJJA_MAX_RETRIES: ${CNPJJA_MAX_RETRIES:-}
      CNPJJA_TIMEOUT: ${CNPJJA_TIMEOUT:-}
      COLORS_CHART_CYAN_LIGHT: ${COLORS_CHART_CYAN_LIGHT:-}
      COLORS_CHART_CYAN_VERY_LIGHT: ${COLORS_CHART_CYAN_VERY_LIGHT:-}
      COLORS_CYAN: ${COLORS_CYAN:-}
      COLORS_CYAN2: ${COLORS_CYAN2:-}
      COLORS_CYAN3: ${COLORS_CYAN3:-}
      COLORS_CYAN4: ${COLORS_CYAN4:-}
      COLORS_CYAN5: ${COLORS_CYAN5:-}
      COLORS_DARK_DARKBLUE: ${COLORS_DARK_DARKBLUE:-}
      COLORS_DARK_DARKBLUE2: ${COLORS_DARK_DARKBLUE2:-}
      COLORS_DARK_DARKBLUE3: ${COLORS_DARK_DARKBLUE3:-}
      COLORS_DARK_DARKBLUE4: ${COLORS_DARK_DARKBLUE4:-}
      COLORS_DARK_SLATE: ${COLORS_DARK_SLATE:-}
      COLORS_DARK_SLATE2: ${COLORS_DARK_SLATE2:-}
      COLORS_DARK_SLATE3: ${COLORS_DARK_SLATE3:-}
      COLORS_DARK_TEXT_PRIMARY: ${COLORS_DARK_TEXT_PRIMARY:-}
      COLORS_DARK_TEXT_QUATERNARY: ${COLORS_DARK_TEXT_QUATERNARY:-}
      COLORS_DARK_TEXT_SECONDARY: ${COLORS_DARK_TEXT_SECONDARY:-}
      COLORS_DARK_TEXT_TERTIARY: ${COLORS_DARK_TEXT_TERTIARY:-}
      COLORS_ERROR_RED: ${COLORS_ERROR_RED:-}
      COLORS_ERROR_RED_LIGHT: ${COLORS_ERROR_RED_LIGHT:-}
      COLORS_GREEN: ${COLORS_GREEN:-}
      COLORS_GREEN2: ${COLORS_GREEN2:-}
      COLORS_LIGHT_DARKBLUE: ${COLORS_LIGHT_DARKBLUE:-}
      COLORS_LIGHT_DARKBLUE2: ${COLORS_LIGHT_DARKBLUE2:-}
      COLORS_LIGHT_DARKBLUE3: ${COLORS_LIGHT_DARKBLUE3:-}
      COLORS_LIGHT_DARKBLUE4: ${COLORS_LIGHT_DARKBLUE4:-}
      COLORS_LIGHT_SLATE: ${COLORS_LIGHT_SLATE:-}
      COLORS_LIGHT_SLATE2: ${COLORS_LIGHT_SLATE2:-}
      COLORS_LIGHT_SLATE3: ${COLORS_LIGHT_SLATE3:-}
      COLORS_LIGHT_TEXT_PRIMARY: ${COLORS_LIGHT_TEXT_PRIMARY:-}
      COLORS_LIGHT_TEXT_QUATERNARY: ${COLORS_LIGHT_TEXT_QUATERNARY:-}
      COLORS_LIGHT_TEXT_SECONDARY: ${COLORS_LIGHT_TEXT_SECONDARY:-}
      COLORS_LIGHT_TEXT_TERTIARY: ${COLORS_LIGHT_TEXT_TERTIARY:-}
      COLORS_OPACITY_TRANSLUCENT: ${COLORS_OPACITY_TRANSLUCENT:-}
      COLORS_OPACITY_TRANSLUCENT2: ${COLORS_OPACITY_TRANSLUCENT2:-}
      COLORS_OPACITY_TRANSLUCENT3: ${COLORS_OPACITY_TRANSLUCENT3:-}
      COLORS_OPACITY_TRANSLUCENT4: ${COLORS_OPACITY_TRANSLUCENT4:-}
      COLORS_OPACITY_TRANSLUCENT_LIGHT: ${COLORS_OPACITY_TRANSLUCENT_LIGHT:-}
      COLORS_OPACITY_TRANSLUCENT_LIGHT2: ${COLORS_OPACITY_TRANSLUCENT_LIGHT2:-}
      COLORS_OPACITY_TRANSLUCENT_MEDIUM: ${COLORS_OPACITY_TRANSLUCENT_MEDIUM:-}
      COLORS_OPACITY_TRANSLUCENT_MEDIUM2: ${COLORS_OPACITY_TRANSLUCENT_MEDIUM2:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT2: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT2:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT3: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT3:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT4: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT4:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT5: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT5:-}
      COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT6: ${COLORS_OPACITY_TRANSLUCENT_VERY_LIGHT6:-}
      COLORS_PAYMENT_ERROR: ${COLORS_PAYMENT_ERROR:-}
      COLORS_PAYMENT_PLACEHOLDER: ${COLORS_PAYMENT_PLACEHOLDER:-}
      COLORS_PAYMENT_TEXT: ${COLORS_PAYMENT_TEXT:-}
      COLORS_PRIMARY: ${COLORS_PRIMARY:-}
      COLORS_PRIMARY_DARK: ${COLORS_PRIMARY_DARK:-}
      COLORS_PRIMARY_DARKER: ${COLORS_PRIMARY_DARKER:-}
      COLORS_PRIMARY_LIGHT: ${COLORS_PRIMARY_LIGHT:-}
      COLORS_PRIMARY_LIGHTER: ${COLORS_PRIMARY_LIGHTER:-}
      COLORS_QUASAR_ACCENT: ${COLORS_QUASAR_ACCENT:-}
      COLORS_QUASAR_DARK: ${COLORS_QUASAR_DARK:-}
      COLORS_QUASAR_PRIMARY: ${COLORS_QUASAR_PRIMARY:-}
      COLORS_RED: ${COLORS_RED:-}
      COLORS_RED2: ${COLORS_RED2:-}
      COLORS_SOCIAL_INSTAGRAM: ${COLORS_SOCIAL_INSTAGRAM:-}
      COLORS_SOCIAL_MESSENGER: ${COLORS_SOCIAL_MESSENGER:-}
      COLORS_SOCIAL_TELEGRAM: ${COLORS_SOCIAL_TELEGRAM:-}
      COLORS_SOCIAL_WHATSAPP: ${COLORS_SOCIAL_WHATSAPP:-}
      COLORS_WHITE: ${COLORS_WHITE:-}
      COLORS_YELLOW: ${COLORS_YELLOW:-}
      COLORS_YELLOW2: ${COLORS_YELLOW2:-}
      DATABASE_CONNECTION_DATABASE: ${DATABASE_CONNECTION_DATABASE:-}
      DATABASE_CONNECTION_HOST: ${DATABASE_CONNECTION_HOST:-}
      DATABASE_CONNECTION_PASSWORD: ${DATABASE_CONNECTION_PASSWORD:-}
      DATABASE_CONNECTION_PORT: ${DATABASE_CONNECTION_PORT:-}
      DATABASE_CONNECTION_USERNAME: ${DATABASE_CONNECTION_USERNAME:-}
      DATABASE_MIGRATE: ${DATABASE_MIGRATE:-}
      DATABASE_URL: ${DATABASE_URL:-}
      EMAIL_DRIVER: ${EMAIL_DRIVER:-}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-}
      EMAIL_OTP_TEMPLATE_HTML: ${EMAIL_OTP_TEMPLATE_HTML:-}
      EMAIL_OTP_TEMPLATE_SUBJECT: ${EMAIL_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_OTP_TEMPLATE_TEXT: ${EMAIL_OTP_TEMPLATE_TEXT:-}
      EMAIL_REPLY_TO_ADDRESS: ${EMAIL_REPLY_TO_ADDRESS:-}
      EMAIL_REPLY_TO_NAME: ${EMAIL_REPLY_TO_NAME:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_HTML: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_HTML:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_SUBJECT: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_RESET_PASSWORD_OTP_TEMPLATE_TEXT: ${EMAIL_RESET_PASSWORD_OTP_TEMPLATE_TEXT:-}
      EMAIL_SES_ACCESS_KEY_ID: ${EMAIL_SES_ACCESS_KEY_ID:-}
      EMAIL_SES_REGION: ${EMAIL_SES_REGION:-}
      EMAIL_SES_SECRET_ACCESS_KEY: ${EMAIL_SES_SECRET_ACCESS_KEY:-}
      EMAIL_SMTP_AUTH_PASSWORD: ${EMAIL_SMTP_AUTH_PASSWORD:-}
      EMAIL_SMTP_AUTH_USER: ${EMAIL_SMTP_AUTH_USER:-}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-}
      EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_HTML: ${EMAIL_VERIFICATION_OTP_TEMPLATE_HTML:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_SUBJECT: ${EMAIL_VERIFICATION_OTP_TEMPLATE_SUBJECT:-}
      EMAIL_VERIFICATION_OTP_TEMPLATE_TEXT: ${EMAIL_VERIFICATION_OTP_TEMPLATE_TEXT:-}
      FILES_LOCAL_FOLDER: ${FILES_LOCAL_FOLDER:-}
      FILES_LOCAL_SIGNING_KEY: ${FILES_LOCAL_SIGNING_KEY:-}
      FILES_PROVIDER: ${FILES_PROVIDER:-}
      FILES_S3_ACCESS_KEY_ID: ${FILES_S3_ACCESS_KEY_ID:-}
      FILES_S3_BASE_URL: ${FILES_S3_BASE_URL:-}
      FILES_S3_BUCKET: ${FILES_S3_BUCKET:-}
      FILES_S3_REGION: ${FILES_S3_REGION:-}
      FILES_S3_SECRET_ACCESS_KEY: ${FILES_S3_SECRET_ACCESS_KEY:-}
      FIPE_BASE_URL: ${FIPE_BASE_URL:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENAI_MAX_RETRIES: ${OPENAI_MAX_RETRIES:-}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION:-}
      OPENAI_TIMEOUT: ${OPENAI_TIMEOUT:-}
      OPENAI_VALIDATION_MODEL: ${OPENAI_VALIDATION_MODEL:-}
      PAYMENT_ASAAS_API_KEY: ${PAYMENT_ASAAS_API_KEY:-}
      PAYMENT_ASAAS_BASE_URL: ${PAYMENT_ASAAS_BASE_URL:-}
      PAYMENT_ASAAS_ENABLED: ${PAYMENT_ASAAS_ENABLED:-}
      PAYMENT_ASAAS_WEBHOOK_TOKEN: ${PAYMENT_ASAAS_WEBHOOK_TOKEN:-}
      PAYMENT_DEFAULT_PROVIDER: ${PAYMENT_DEFAULT_PROVIDER:-}
      PAYMENT_ENABLED_METHOD_TYPES: ${PAYMENT_ENABLED_METHOD_TYPES:-}
      PAYMENT_MERCADO_PAGO_ACCESS_TOKEN: ${PAYMENT_MERCADO_PAGO_ACCESS_TOKEN:-}
      PAYMENT_MERCADO_PAGO_ENABLED: ${PAYMENT_MERCADO_PAGO_ENABLED:-}
      PAYMENT_MERCADO_PAGO_PUBLIC_KEY: ${PAYMENT_MERCADO_PAGO_PUBLIC_KEY:-}
      PAYMENT_MERCADO_PAGO_WEBHOOK_SECRET: ${PAYMENT_MERCADO_PAGO_WEBHOOK_SECRET:-}
      PAYMENT_PAGAR_ME_API_KEY: ${PAYMENT_PAGAR_ME_API_KEY:-}
      PAYMENT_PAGAR_ME_BASE_URL: ${PAYMENT_PAGAR_ME_BASE_URL:-}
      PAYMENT_PAGAR_ME_ENABLED: ${PAYMENT_PAGAR_ME_ENABLED:-}
      PAYMENT_PAGAR_ME_ENCRYPTION_KEY: ${PAYMENT_PAGAR_ME_ENCRYPTION_KEY:-}
      PAYMENT_PAGAR_ME_WEBHOOK_SECRET: ${PAYMENT_PAGAR_ME_WEBHOOK_SECRET:-}
      PAYMENT_STRIPE_ENABLED: ${PAYMENT_STRIPE_ENABLED:-}
      PAYMENT_STRIPE_PUBLISHABLE_KEY: ${PAYMENT_STRIPE_PUBLISHABLE_KEY:-}
      PAYMENT_STRIPE_SECRET_KEY: ${PAYMENT_STRIPE_SECRET_KEY:-}
      PAYMENT_STRIPE_WEBHOOK_SECRET: ${PAYMENT_STRIPE_WEBHOOK_SECRET:-}
      PREDIAL_AI_API_KEY: ${PREDIAL_AI_API_KEY:-}
      PREDIAL_AI_API_URL: ${PREDIAL_AI_API_URL:-}
      PREDIAL_AI_MODEL: ${PREDIAL_AI_MODEL:-}
      PREDIAL_AI_PROVIDER: ${PREDIAL_AI_PROVIDER:-}
      PREDIAL_ENABLED: ${PREDIAL_ENABLED:-}
      PREDIAL_GEOFENCE_DISTANCE: ${PREDIAL_GEOFENCE_DISTANCE:-}
      PREDIAL_MAX_PHOTO_SIZE: ${PREDIAL_MAX_PHOTO_SIZE:-}
      PREDIAL_NOTIFICATION_ENABLED: ${PREDIAL_NOTIFICATION_ENABLED:-}
      PREDIAL_TRIAL_DURATION_DAYS: ${PREDIAL_TRIAL_DURATION_DAYS:-}
      PUBLIC_APP_NAME: ${PUBLIC_APP_NAME:-}
      PUBLIC_AUTH_BACKGROUND_LOGO_PATH: ${PUBLIC_AUTH_BACKGROUND_LOGO_PATH:-}
      PUBLIC_AUTH_SIDE_LOGO_PATH: ${PUBLIC_AUTH_SIDE_LOGO_PATH:-}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:-}
      PUBLIC_DARK_MODE_FOOTER_LOGO_PATH: ${PUBLIC_DARK_MODE_FOOTER_LOGO_PATH:-}
      PUBLIC_DARK_MODE_LOGO_PATH: ${PUBLIC_DARK_MODE_LOGO_PATH:-}
      PUBLIC_DEFAULT_THEME: ${PUBLIC_DEFAULT_THEME:-}
      PUBLIC_FAVICON_PATH: ${PUBLIC_FAVICON_PATH:-}
      PUBLIC_LIGHT_MODE_FOOTER_LOGO_PATH: ${PUBLIC_LIGHT_MODE_FOOTER_LOGO_PATH:-}
      PUBLIC_LIGHT_MODE_LOGO_PATH: ${PUBLIC_LIGHT_MODE_LOGO_PATH:-}
      PUBLIC_MENU_REFRESH_INTERVAL: ${PUBLIC_MENU_REFRESH_INTERVAL:-}
      PUBLIC_SOCIAL_LINKS_FACEBOOK: ${PUBLIC_SOCIAL_LINKS_FACEBOOK:-}
      PUBLIC_SOCIAL_LINKS_GITHUB: ${PUBLIC_SOCIAL_LINKS_GITHUB:-}
      PUBLIC_SOCIAL_LINKS_INSTAGRAM: ${PUBLIC_SOCIAL_LINKS_INSTAGRAM:-}
      PUBLIC_SOCIAL_LINKS_LINKEDIN: ${PUBLIC_SOCIAL_LINKS_LINKEDIN:-}
      PUBLIC_SOCIAL_LINKS_TWITTER: ${PUBLIC_SOCIAL_LINKS_TWITTER:-}
      QUEUES_DEFAULT_JOB_OPTIONS_ATTEMPTS: ${QUEUES_DEFAULT_JOB_OPTIONS_ATTEMPTS:-}
      QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_DELAY: ${QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_DELAY:-}
      QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_TYPE: ${QUEUES_DEFAULT_JOB_OPTIONS_BACKOFF_TYPE:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_AGE: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_AGE:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_COUNT: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_COMPLETE_COUNT:-}
      QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_FAIL_AGE: ${QUEUES_DEFAULT_JOB_OPTIONS_REMOVE_ON_FAIL_AGE:-}
      QUEUES_WORKERS_DISABLED: ${QUEUES_WORKERS_DISABLED:-}
      QUEUES_WORKERS_ENABLED: ${QUEUES_WORKERS_ENABLED:-}
      REDIS_AUTH_DB: ${REDIS_AUTH_DB:-}
      REDIS_CACHE_DB: ${REDIS_CACHE_DB:-}
      REDIS_CONNECTION_HOST: ${REDIS_CONNECTION_HOST:-}
      REDIS_CONNECTION_PASSWORD: ${REDIS_CONNECTION_PASSWORD:-}
      REDIS_CONNECTION_PORT: ${REDIS_CONNECTION_PORT:-}
      REDIS_PREFIX: ${REDIS_PREFIX:-}
      REDIS_QUEUE_DB: ${REDIS_QUEUE_DB:-}
      REDIS_URL: ${REDIS_URL:-}
      RPA_CDP_CONNECTION_INITIAL_DELAY: ${RPA_CDP_CONNECTION_INITIAL_DELAY:-}
      RPA_CDP_CONNECTION_RETRIES: ${RPA_CDP_CONNECTION_RETRIES:-}
      RPA_CDP_CONNECTION_RETRY_DELAY: ${RPA_CDP_CONNECTION_RETRY_DELAY:-}
      RPA_CONCURRENCY: ${RPA_CONCURRENCY:-}
      RPA_CONTAINER_BROWSER_IMAGE: ${RPA_CONTAINER_BROWSER_IMAGE:-}
      RPA_CONTAINER_TIMEOUT: ${RPA_CONTAINER_TIMEOUT:-}
      RPA_CONTAINER_USER_AGENT: ${RPA_CONTAINER_USER_AGENT:-}
      RPA_CONTAINER_VIEWPORT_HEIGHT: ${RPA_CONTAINER_VIEWPORT_HEIGHT:-}
      RPA_CONTAINER_VIEWPORT_WIDTH: ${RPA_CONTAINER_VIEWPORT_WIDTH:-}
      RPA_DEBUG: ${RPA_DEBUG:-}
      RPA_ENCRYPTION_KEY: ${RPA_ENCRYPTION_KEY:-}
      RPA_LOCAL_BROWSER_ARGS: ${RPA_LOCAL_BROWSER_ARGS:-}
      RPA_LOCAL_BROWSER_HEADLESS: ${RPA_LOCAL_BROWSER_HEADLESS:-}
      RPA_LOCAL_BROWSER_PERMISSIONS: ${RPA_LOCAL_BROWSER_PERMISSIONS:-}
      RPA_LOCAL_BROWSER_SLOW_MO: ${RPA_LOCAL_BROWSER_SLOW_MO:-}
      RPA_LOCAL_BROWSER_VIEWPORT_HEIGHT: ${RPA_LOCAL_BROWSER_VIEWPORT_HEIGHT:-}
      RPA_LOCAL_BROWSER_VIEWPORT_WIDTH: ${RPA_LOCAL_BROWSER_VIEWPORT_WIDTH:-}
      RPA_MODE: ${RPA_MODE:-}
      RPA_TIMEOUT_BATCH_INACTIVITY_DEFAULT: ${RPA_TIMEOUT_BATCH_INACTIVITY_DEFAULT:-}
      RPA_TIMEOUT_JOB_INACTIVITY_DEFAULT: ${RPA_TIMEOUT_JOB_INACTIVITY_DEFAULT:-}
      SMS_CODE_TEMPLATE: ${SMS_CODE_TEMPLATE:-}
      SMS_DRIVER: ${SMS_DRIVER:-}
      SMS_IAGENTE_BASE_URL: ${SMS_IAGENTE_BASE_URL:-}
      SMS_IAGENTE_PASSWORD: ${SMS_IAGENTE_PASSWORD:-}
      SMS_IAGENTE_USERNAME: ${SMS_IAGENTE_USERNAME:-}
      SMS_RESET_CODE_TEMPLATE: ${SMS_RESET_CODE_TEMPLATE:-}
      SUBSCRIPTIONS_GRACE_PERIOD_DAYS: ${SUBSCRIPTIONS_GRACE_PERIOD_DAYS:-}
      SUBSCRIPTIONS_SCHEDULES_GENERATE_RENEWAL_INVOICES: ${SUBSCRIPTIONS_SCHEDULES_GENERATE_RENEWAL_INVOICES:-}
      SUBSCRIPTIONS_SCHEDULES_INACTIVATE_EXPIRED_SUBSCRIPTIONS: ${SUBSCRIPTIONS_SCHEDULES_INACTIVATE_EXPIRED_SUBSCRIPTIONS:-}
      SUBSCRIPTIONS_SCHEDULES_PROCESS_EXPIRED_TRIALS: ${SUBSCRIPTIONS_SCHEDULES_PROCESS_EXPIRED_TRIALS:-}
      SUBSCRIPTIONS_SCHEDULES_PROCESS_SCHEDULED_DOWNGRADES: ${SUBSCRIPTIONS_SCHEDULES_PROCESS_SCHEDULED_DOWNGRADES:-}

    depends_on:
      - postgres
      - redis
    volumes:
      - storage_data:/app/storage
  chromium:
    image: registry.gitlab.com/paganiniinformatica/paganini-app-boilerplate/chromium:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/rpa/chromium.Dockerfile
    restart: no
    command: ["echo", "Exiting..."]

volumes:
  storage_data:
    driver: local
  podman_socket:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
